In [1]:
a = 5
a

5

In [2]:
print(a)

5


In [10]:
def fun():
    for i in range(10):
        print(i)

In [11]:
fun()

0
1
2
3
4
5
6
7
8
9


In [15]:
import numpy as np
# 使用时先引用

In [16]:
arr = np.array([1,2,3,4])
arr
# 创建n维数组 np.array()

array([1, 2, 3, 4])

In [17]:
arr.ndim
# np.array的属性ndim表示数组的维度

1

In [23]:
arr.shape
# np.array的属性ndim表示数组的结构（长宽高）

(4,)

In [19]:
arr.size
# np.array的属性zize表示数组中的个数

4

In [21]:
#np.zeros(shape):返回一个n维0填充的数组
arr1 = np.zeros((2,3,4))

In [22]:
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
#np.ones(shape):返回一个n维1填充的数组
arr2 = np.ones((2,3,4))
arr2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
#np.zeros_like(数组) np.ones_like(数组)
#对数组进行0/1化，生成新数组
a = np.zeros_like(arr1)
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
#np.full(结构，值):将某个结构的数组全部赋同样值
b = np.full((2,2,3),6)
b

array([[[6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6]]])

In [29]:
b = np.full((2,2,3),np.pi)
b

array([[[3.14159265, 3.14159265, 3.14159265],
        [3.14159265, 3.14159265, 3.14159265]],

       [[3.14159265, 3.14159265, 3.14159265],
        [3.14159265, 3.14159265, 3.14159265]]])

In [31]:
#np.linspace(start,end,num = n)
arr3 = np.linspace(1,6,num = 5,endpoint = True)
arr3

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [32]:
#?np.function:查函数参数
?np.linspace

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x0000025AF724D800>
File:            d:\anaconda\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that 

In [35]:
#np.fromfunction(lambda x,y,...:...,(nx,ny,...))
#由lambda表达式创建出n维数组
m = np.fromfunction(lambda x,y,z:(x+1)*(y+1)*(z+1),(6,6,6))

In [34]:
m

array([[[  1.,   2.,   3.,   4.,   5.,   6.],
        [  2.,   4.,   6.,   8.,  10.,  12.],
        [  3.,   6.,   9.,  12.,  15.,  18.],
        [  4.,   8.,  12.,  16.,  20.,  24.],
        [  5.,  10.,  15.,  20.,  25.,  30.],
        [  6.,  12.,  18.,  24.,  30.,  36.]],

       [[  2.,   4.,   6.,   8.,  10.,  12.],
        [  4.,   8.,  12.,  16.,  20.,  24.],
        [  6.,  12.,  18.,  24.,  30.,  36.],
        [  8.,  16.,  24.,  32.,  40.,  48.],
        [ 10.,  20.,  30.,  40.,  50.,  60.],
        [ 12.,  24.,  36.,  48.,  60.,  72.]],

       [[  3.,   6.,   9.,  12.,  15.,  18.],
        [  6.,  12.,  18.,  24.,  30.,  36.],
        [  9.,  18.,  27.,  36.,  45.,  54.],
        [ 12.,  24.,  36.,  48.,  60.,  72.],
        [ 15.,  30.,  45.,  60.,  75.,  90.],
        [ 18.,  36.,  54.,  72.,  90., 108.]],

       [[  4.,   8.,  12.,  16.,  20.,  24.],
        [  8.,  16.,  24.,  32.,  40.,  48.],
        [ 12.,  24.,  36.,  48.,  60.,  72.],
        [ 16.,  32.,  48.,  

In [37]:
#创建n维数组时，可以指定数据类型，加入dtype
ar = np.array([1,2,3,4,5],dtype = np.float64)
ar

array([1., 2., 3., 4., 5.])

In [38]:
?np.array

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [39]:
#创建n维数组时，若对象类型不统一，会自动转化为更大的数据类型
arr = np.array([1,2,3,True,'a',False])
arr

array(['1', '2', '3', 'True', 'a', 'False'], dtype='<U21')

In [41]:
#产生随机数
#根据指定范围产生指定结构的随机数数组
r = np.random.randint(0,100,(2,3,4)) #整数数组
r1 = np.random.randn(2,3,4) #符合正态分布,均值为0，方差为1
r2 = np.random.uniform(0,100,(2,3,4)) #随机数


In [42]:
?np.random.randn

Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

In [43]:
r

array([[[35, 87, 11, 81],
        [27, 78, 50, 28],
        [92, 62, 97, 58]],

       [[13, 69, 43, 75],
        [51,  3,  5, 65],
        [54, 67, 56, 49]]], dtype=int32)

In [44]:
r1

array([[[ 0.15947704,  0.83873113,  0.24217132, -1.53566968],
        [-0.44742886,  0.5219893 , -1.05947937,  0.13873801],
        [-0.38070498,  0.70313284,  1.19865155,  1.14208967]],

       [[-1.20616901,  0.46086281, -0.89834509, -0.10731653],
        [-1.46647356, -0.1090317 ,  1.4472347 ,  0.11962009],
        [ 0.61754947, -0.75058987, -1.06625445, -0.52809797]]])

In [45]:
r2

array([[[86.96841075, 15.65497266, 52.59392202, 89.79645442],
        [50.79821916, 55.78869672, 63.22647841, 33.67863203],
        [84.83294904, 53.42905588, 29.67985943, 74.63658171]],

       [[ 0.48673028, 15.92402186, 20.68612825, 91.15279067],
        [81.73648901, 57.52173252, 38.24231982, 26.71716125],
        [ 3.88526347, 52.93722658, 27.85418239, 72.82422041]]])