In [4]:
#数据的合并
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [5]:
arr = np.random.randint(0,10,(3,3))
arr

array([[9, 0, 8],
       [2, 1, 0],
       [9, 9, 6]], dtype=int32)

In [6]:
#numpy中的concatenate支持多维数组数据合并
arr1 = np.concatenate((arr,arr),axis = 0)
arr1

array([[9, 0, 8],
       [2, 1, 0],
       [9, 9, 6],
       [9, 0, 8],
       [2, 1, 0],
       [9, 9, 6]], dtype=int32)

In [7]:
arr2 = np.concatenate((arr,arr),axis = 1)
arr2

array([[9, 0, 8, 9, 0, 8],
       [2, 1, 0, 2, 1, 0],
       [9, 9, 6, 9, 9, 6]], dtype=int32)

In [8]:
#利用列表表达式创建字典，再利用字典创建DataFrame
dict = {i:[p*i for p in range(3)] for i in range(10)}
dict

{0: [0, 0, 0],
 1: [0, 1, 2],
 2: [0, 2, 4],
 3: [0, 3, 6],
 4: [0, 4, 8],
 5: [0, 5, 10],
 6: [0, 6, 12],
 7: [0, 7, 14],
 8: [0, 8, 16],
 9: [0, 9, 18]}

In [9]:
def fun1(cols,index):
    data = {i:[str(p)+i for p in index] for i in cols}
    return pd.DataFrame(data,columns = cols,index = index)
fun1(['a','b'],['1','2'])

,a,b
1,1a,1b
2,2a,2b


In [10]:
#pandas中的concat可以实现基本的DataFrame的间数据合并
#pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, sort=None,verify_integrity=False, sort=None, copy=True)
df1 = fun1(["a","b"],[1,2])
df2 = fun1(["a","b"],[3,4])
display(df1,df2)

,a,b
1,1a,1b
2,2a,2b


,a,b
3,3a,3b
4,4a,4b


In [11]:
pd.concat((df1,df2),axis = 0) #axis参数可修改合并的方向

,a,b
1,1a,1b
2,2a,2b
3,3a,3b
4,4a,4b


In [12]:
#合并时索引可以重复
df3 = fun1(["a","b","c"],[1,2,3])
df4 = fun1(["a","b","c"],[3,4])
pd.concat((df3,df4))

,a,b,c
1,1a,1b,1c
2,2a,2b,2c
3,3a,3b,3c
3,3a,3b,3c
4,4a,4b,4c


In [13]:
#可以在合并时重新设置索引
pd.concat((df3,df4), ignore_index = True)

,a,b,c
0,1a,1b,1c
1,2a,2b,2c
2,3a,3b,3c
3,3a,3b,3c
4,4a,4b,4c


In [14]:
#合并时，可能出现列名不匹配的情况，利用join与join_axes参数设置数据连接的方式
#1.外连接outer（默认）相当于数据库中的全外连接（求并集）
#2.内连接inner，只显示互相匹配得上的数据（求交集）

In [15]:
d1 = fun1(["A","B","C"],[1,3,5])
d2 = fun1(["a","b","c"],[2,3,4])
display(d1,d2)

,A,B,C
1,1A,1B,1C
3,3A,3B,3C
5,5A,5B,5C


,a,b,c
2,2a,2b,2c
3,3a,3b,3c
4,4a,4b,4c


In [19]:
pd.concat((d1,d2),axis = 1,join = "outer")

,A,B,C,a,b,c
1,1A,1B,1C,NaN,NaN,NaN
3,3A,3B,3C,3a,3b,3c
5,5A,5B,5C,NaN,NaN,NaN
2,NaN,NaN,NaN,2a,2b,2c
4,NaN,NaN,NaN,4a,4b,4c


In [20]:
pd.concat((d1,d2),axis = 1,join = "inner")

,A,B,C,a,b,c
3,3A,3B,3C,3a,3b,3c


In [38]:
#3.左/右连接，设置合并标准（以其中一个表为标准）
d3 = fun1(["A","B","C"],[1,3,5])
d4 = fun1(["A","C","D"],[1,3,4])
df1 = pd.concat((d3,d4))

In [39]:
df2 = df1[d4.columns]
df2

,A,C,D
1,1A,1C,NaN
3,3A,3C,NaN
5,5A,5C,NaN
1,1A,1C,1D
3,3A,3C,3D
4,4A,4C,4D


In [40]:
df3 = df1[d3.columns]
df3

,A,B,C
1,1A,1B,1C
3,3A,3B,3C
5,5A,5B,5C
1,1A,NaN,1C
3,3A,NaN,3C
4,4A,NaN,4C


In [61]:
#pandas中的merge较为常用，在进行数据合并时，一定是基于某一列进行数据合并的（默认内连接，默认根据所有列名全匹配）
#pd.merge(left ,right, how = 'inner', on = None, left_on = None, right_on = None, left_index = False, right_index = False, sort = False, suffixes = ('_x', '_y'), copy = None, indicator = False, validate = None,)
da1 = DataFrame({"employee":["Sheldon","Penny", "Kite"],"dept":["hr","marketing","sales"]})
da2 = DataFrame({"employee":["Sheldon","Penny","Bill"],"work_time":[2,4,5]})
display(da1,da2)

,employee,dept
0,Sheldon,hr
1,Penny,marketing
2,Kite,sales


,employee,work_time
0,Sheldon,2
1,Penny,4
2,Bill,5


In [62]:
pd.merge(da1,da2)

,employee,dept,work_time
0,Sheldon,hr,2
1,Penny,marketing,4


In [63]:
?pd.merge

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning:

In [64]:
#一对多场景
da3 = DataFrame({"employee":["Sheldon","Penny", "Penny"],"dept":["hr","marketing","sales"]})
da4 = DataFrame({"employee":["Sheldon","Penny","Bill"],"work_time":[2,4,5]})
pd.merge(da3,da4)

,employee,dept,work_time
0,Sheldon,hr,2
1,Penny,marketing,4
2,Penny,sales,4


In [65]:
#利用参数on，可确定根据哪一列参数进行合并
d1 = DataFrame({"employee":["Sheldon","Penny", "Lanard"],"dept":["hr","marketing","sales"],"salary":[10000,9000,8500]})
d2 = DataFrame({"employee":["Sheldon","Penny", "Kite"],"dept":["marketing","marketing","sales"],"work_time":[2,4,5]})
display(d1,d2)

,employee,dept,salary
0,Sheldon,hr,10000
1,Penny,marketing,9000
2,Lanard,sales,8500


,employee,dept,work_time
0,Sheldon,marketing,2
1,Penny,marketing,4
2,Kite,sales,5


In [66]:
pd.merge(d1,d2)

,employee,dept,salary,work_time
0,Penny,marketing,9000,4


In [67]:
pd.merge(d1,d2,on = "employee")

,employee,dept_x,salary,dept_y,work_time
0,Sheldon,hr,10000,marketing,2
1,Penny,marketing,9000,marketing,4


In [68]:
 pd.merge(d1,d2,on = "dept")

,employee_x,dept,salary,employee_y,work_time
0,Penny,marketing,9000,Sheldon,2
1,Penny,marketing,9000,Penny,4
2,Lanard,sales,8500,Kite,5


In [69]:
#若左右两表格所需要匹配的列名不同，可用left_on与right_on参数进行匹配
pd.merge(d1,d2,left_on="employee", right_on="employee", how="outer")

,employee,dept_x,salary,dept_y,work_time
0,Kite,NaN,NaN,sales,5.0
1,Lanard,sales,8500.0,NaN,NaN
2,Penny,marketing,9000.0,marketing,4.0
3,Sheldon,hr,10000.0,marketing,2.0


In [70]:
#可用how参数改变连接方式：内外左右
pd.merge(d1,d2,left_on="employee", right_on="employee", how="left")

,employee,dept_x,salary,dept_y,work_time
0,Sheldon,hr,10000,marketing,2.0
1,Penny,marketing,9000,marketing,4.0
2,Lanard,sales,8500,NaN,NaN


In [71]:
pd.merge(d1,d2,left_on="employee", right_on="employee", how="right")

,employee,dept_x,salary,dept_y,work_time
0,Sheldon,hr,10000.0,marketing,2
1,Penny,marketing,9000.0,marketing,4
2,Kite,NaN,NaN,sales,5
